- name: "Wait until teamcity starts"
  wait_for:
    host: 127.0.0.1
    port: "{{ teamcity_server_bind_port }}"
    delay: 10
    timeout: 30

- name: "Wait for auto-configuration"
  uri:
    url: "http://127.0.0.1:{{ teamcity_server_bind_port }}/showAgreement.html"
    method: GET
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 20

- name: "Accept License"
  uri:
    url: "http://127.0.0.1:{{ teamcity_server_bind_port }}/showAgreement.html"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "accept=true"
    status_code: 302
    creates: "{{ teamcity_server_license_accepted }}"

- name: "Create license-accepted"
  file:
    path: "{{ teamcity_server_license_accepted }}"
    state: touch
    owner: "{{ teamcity_system_user }}"
    group: "{{ teamcity_system_group }}"
    mode: 0644
    access_time: preserve
    modification_time: preserve

- name: "Ensure teamcity is running"
  service:
    name: teamcity-server
    state: started
    enabled: yes

- name: "Get Authentication Token"
  shell: "grep -ioE 'Super user authentication token: (.*)' {{ teamcity_server_dir }}/logs/teamcity-server.log | tail -1 | sed 's/.*token:[ \\\"]*\\([a-zA-Z0-9]*\\).*/\\1/'"
  register: _token
  check_mode: no
  args:
    creates: "{{ teamcity_server_admin_user_created }}"

- name: "Generate base64 for auth"
  set_fact:
    _base64_token: "{{ (':'~_token.stdout) | b64encode }}"

- name: "Create Admin User"
  uri:
    url: "http://127.0.0.1:{{ teamcity_server_bind_port }}/httpAuth/app/rest/users"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ _base64_token }}"
    body:
      username: "{{ teamcity_admin_user }}"
      password: "{{ teamcity_admin_password }}"
    body_format: json
    creates: "{{ teamcity_server_admin_user_created }}"

- name: "Setup Admin User"
  uri:
    url: "http://127.0.0.1:{{ teamcity_server_bind_port }}/httpAuth/app/rest/users/username:{{ teamcity_admin_user }}/roles/SYSTEM_ADMIN/g/"
    method: PUT
    headers:
      Content-Type: "application/json"
      Authorization: "Basic {{ _base64_token }}"
    body_format: json
    creates: "{{ teamcity_server_admin_user_created }}"

- name: "Create admin-user-created"
  file:
    path: "{{ teamcity_server_admin_user_created }}"
    state: touch
    owner: "{{ teamcity_system_user }}"
    group: "{{ teamcity_system_group }}"
    mode: 0644
    access_time: preserve
    modification_time: preserve
